Repository baserproject/basercms, pull requests merged in 2019-11, with the labels that each got.

#1295 fix #1294 メールプラグイン選択リストで特定の文字で終わると文字化けを起こす問題を解決
  lib/Baser/Plugin/Mail/Model/MailField.php
Labels: Bug

#1286 メールフォームの拡張入力チェックに正規表現チェックを追加
  app/webroot/theme/admin-third/MailFields/admin/form.php
  lib/Baser/Plugin/Mail/Model/MailField.php
  lib/Baser/Plugin/Mail/Model/MailMessage.php
  lib/Baser/Plugin/Mail/View/Helper/MailfieldHelper.php
  lib/Baser/Plugin/Mail/View/Helper/MailformHelper.php
  lib/Baser/Plugin/Mail/View/MailFields/admin/form.php
Labels: Review

#1297 fix #1296 MailPluginのCSVダウンロードでメモリを消費する問題
  lib/Baser/Test/Case/View/Helper/BcCsvHelperTest.php
  lib/Baser/View/Helper/BcCsvHelper.php
Labels: Todo
