Repository baserproject/basercms, pull requests merged in 2020-07, with the labels that each got.

#1305 メールフォームのテキストタイプフィールドにhtml改行タグを入力すると、通知メール内に改行が反映されるため調整
  lib/Baser/Config/theme/bc_sample/Emails/text/mail_data.php
  lib/Baser/Config/theme/bc_sample/Emails/text/smartphone/mail_data.php
  lib/Baser/Plugin/Mail/Model/MailMessage.php
  lib/Baser/Plugin/Mail/Test/Case/Model/MailMessageTest.php
  lib/Baser/Plugin/Mail/View/Emails/text/mail_data.php
  lib/Baser/Plugin/Mail/View/Emails/text/mobile/mail_data.php
Labels: Review

#1476 #1428 CakePHP 2.10.21 にアップデート / PHP 7.4 に対応
  lib/Baser/Event/CakeEventManager.php
  lib/Baser/HACK.txt
  lib/Baser/Network/CakeRequest.php
  lib/Cake/Cache/Engine/FileEngine.php
  lib/Cake/Console/Command/Task/ModelTask.php
  lib/Cake/Console/Command/UpgradeShell.php
  lib/Cake/Console/ConsoleOptionParser.php
  lib/Cake/Console/ConsoleOutput.php
  lib/Cake/Console/Shell.php
  lib/Cake/Console/ShellDispatcher.php
  lib/Cake/Controller/Component/CookieComponent.php
  lib/Cake/Controller/Component/RequestHandlerComponent.php
  lib/Cake/Controller/Component/SessionComponent.php
  lib/Cake/Event/CakeEventManager.php
  lib/Cake/Model/Behavior/ContainableBehavior.php
  lib/Cake/Model/Datasource/CakeSession.php
  lib/Cake/Model/Datasource/Database/Sqlite.php
  lib/Cake/Model/Model.php
  lib/Cake/Model/Permission.php
  lib/Cake/Network/CakeRequest.php
  lib/Cake/Network/CakeSocket.php
  lib/Cake/Network/Http/HttpSocket.php
  lib/Cake/Test/Case/AllControllerTest.php
  lib/Cake/Test/Case/Cache/CacheTest.php
  lib/Cake/Test/Case/Controller/ApplicationControllerTest.php
  lib/Cake/Test/Case/Controller/Component/RequestHandlerComponentTest.php
  lib/Cake/Test/Case/I18n/MultibyteTest.php
  lib/Cake/Test/Case/Model/Datasource/Database/MysqlTest.php
  lib/Cake/Test/Case/View/Helper/FormHelperTest.php
  lib/Cake/Test/Case/View/Helper/RssHelperTest.php
  lib/Cake/Test/Case/View/ViewTest.php
  lib/Cake/TestSuite/CakeTestCase.php
  lib/Cake/TestSuite/CakeTestRunner.php
  lib/Cake/TestSuite/CakeTestSuiteCommand.php
  lib/Cake/TestSuite/CakeTestSuiteDispatcher.php
  lib/Cake/TestSuite/ControllerTestCase.php
  lib/Cake/Utility/CakeText.php
  lib/Cake/Utility/ClassRegistry.php
  lib/Cake/Utility/Folder.php
  lib/Cake/Utility/Sanitize.php
  lib/Cake/Utility/Set.php
  lib/Cake/VERSION.txt
  lib/Cake/View/Helper/FormHelper.php
  lib/Cake/View/Helper/HtmlHelper.php
  lib/Cake/View/Helper/JsBaseEngineHelper.php
Labels: Adjusting, Review, Todo

#1515 fix #1514 【メール】全角カタカナチェックの際にスペースも許可したい問題を解決
  lib/Baser/Plugin/Mail/Model/MailMessage.php
Labels: Review, Reviewed
