Repository baserproject/basercms, pull requests merged in 2020-03, with the labels that each got.

#1372 ローカル環境にローカル用のタスクメモを残しておけるように無視設定を追加
  lib/Baser/VERSION.txt
Labels: Todo

#1388 ログイン画面をスマートフォンに対応した fix #1387
  app/webroot/theme/admin-third/Layouts/admin/default.php
  app/webroot/theme/admin-third/Users/admin/reset_password.php
  app/webroot/theme/admin-third/__assets/css/base/_general.scss
  app/webroot/theme/admin-third/__assets/css/base/_mixin.scss
  app/webroot/theme/admin-third/__assets/css/components/_app.scss
  app/webroot/theme/admin-third/__assets/css/components/_footer.scss
  app/webroot/theme/admin-third/__assets/css/components/_login.scss
  app/webroot/theme/admin-third/__assets/css/components/_main.scss
  app/webroot/theme/admin-third/__assets/css/style.scss
  app/webroot/theme/admin-third/__assets/css/theme/_unknown.scss
  app/webroot/theme/admin-third/css/admin/style.css
Labels: Todo

#1359 記事一覧(タグ)の引数解析を修正
  lib/Baser/Plugin/Blog/Controller/BlogController.php
Labels: Review

#1360 記事一覧(投稿者)の引数解析を修正
  lib/Baser/Plugin/Blog/Controller/BlogController.php
Labels: Review

#1361 記事一覧(カテゴリ)の引数解析を修正
  lib/Baser/Plugin/Blog/Controller/BlogController.php
Labels: Review

#1362 ブログの全体タグ一覧が表示されない問題を修正
  lib/Baser/Plugin/Blog/Controller/BlogController.php
Labels: Review

#1363 ブログカレンダーが崩れる問題を修正
  lib/Baser/Plugin/Blog/View/Elements/widgets/blog_calendar.php
Labels: Review

#1364 記事一覧(日付)の引数解析を修正
  lib/Baser/Plugin/Blog/Controller/BlogController.php
Labels: Review

#1366 初期データについてお気に入りをクレジットのみに変更 fix #1365
  lib/Baser/Config/data/default/user_groups.csv
  lib/Baser/Config/theme/bc_sample/Config/data/default/site_configs.csv
  lib/Baser/Config/theme/bccolumn/Config/data/default/user_groups.csv
  lib/Baser/Config/theme/nada-icons/Config/data/default/user_groups.csv
Labels: Todo

#1371 TravisCI のテストに、php 7.2 / 7.3 を追加
  .travis.yml
  lib/Baser/Test/Case/BcBasicsTest.php
  travis.php.ini
Labels: Todo

#1373 コマンドインストール時の管理画面テーマを admin-third に変更 fix #1368
  lib/Baser/Controller/Component/BcManagerComponent.php
  lib/Baser/Test/Case/Controller/Component/BcManagerComponentTest.php
Labels: Todo

#1376 コンテンツの移動時のエラー判定を厳密化 fix #1375
  lib/Baser/Controller/ContentsController.php
  lib/Baser/Model/Content.php
  lib/Baser/Test/Case/Model/ContentTest.php
  lib/Baser/Test/Fixture/Model/Content/ContentIsMovableFixture.php
Labels: Todo

#1378 fix #1377 ブログカテゴリ一覧 子カテゴリの前の半角スペースがエスケープ文字で表示されてしまう問題を解決
  lib/Baser/Plugin/Blog/Controller/BlogCategoriesController.php
Labels: Review

#1386 fix #1385 インストールページで表示される404にテーマ適応
  lib/Baser/Controller/BcAppController.php
Labels: Review

#1383 CAPTCHA 認証を回避してコメント投稿できる問題を修正
  lib/Baser/Plugin/Blog/Controller/BlogController.php
Labels: Review

#1393 メールフォームでフィールドが１つも存在しない場合フロントページがNotFoundになる問題を改善 fix #1392
  lib/Baser/Plugin/Mail/Model/MailMessage.php
Labels: Bug

#1400 fix #1397 admin-thirdの「WebサイトURL[SSL]」前に自動入力防止用のダミーフィールドを追加
  app/webroot/theme/admin-third/SiteConfigs/admin/form.php
Labels: Todo

#1391 モバイル関連の機能を削除 fix #1390
  lib/Baser/Controller/MaintenanceController.php
  lib/Baser/Controller/MobileController.php
  lib/Baser/Controller/SearchIndicesController.php
  lib/Baser/Controller/UploadsController.php
  lib/Baser/Plugin/Blog/Controller/BlogController.php
  lib/Baser/Plugin/Blog/View/Blog/mobile/default/archives.php
  lib/Baser/Plugin/Blog/View/Blog/mobile/default/index.php
  lib/Baser/Plugin/Blog/View/Blog/mobile/default/posts.php
  lib/Baser/Plugin/Blog/View/Blog/mobile/default/single.php
  lib/Baser/Plugin/Blog/View/Elements/mobile/blog_comment.php
  lib/Baser/Plugin/Blog/View/Elements/mobile/blog_comments.php
  lib/Baser/Plugin/Feed/Controller/FeedController.php
  lib/Baser/Plugin/Feed/View/Feed/mobile/default.php
  lib/Baser/Plugin/Mail/Test/Case/View/Helper/MailHelperTest.php
  lib/Baser/Plugin/Mail/View/Elements/mobile/mail_form.php
  lib/Baser/Plugin/Mail/View/Elements/mobile/mail_input.php
  lib/Baser/Plugin/Mail/View/Mail/mobile/default/confirm.php
  lib/Baser/Plugin/Mail/View/Mail/mobile/default/index.php
  lib/Baser/Plugin/Mail/View/Mail/mobile/default/submit.php
  lib/Baser/View/Elements/mobile/contents_navi.php
  lib/Baser/View/Elements/mobile/google_analytics.php
  lib/Baser/View/Elements/mobile/list_num.php
  lib/Baser/View/Elements/mobile/paginations/default.php
  lib/Baser/View/Helper/BcMobileHelper.php
  lib/Baser/View/Layouts/mobile/default.php
  lib/Baser/View/Layouts/mobile/email/text/default.php
  lib/Baser/View/Pages/mobile/templates/default.php
  lib/Baser/View/SearchIndices/mobile/search.php
Labels: Review

#1402 フロント認証を設定していない場合でもフロントのURLとしてパスワードリセット画面にアクセスできてしまう問題を改善 fix #1379
  lib/Baser/Controller/Component/BcReplacePrefixComponent.php
  lib/Baser/Test/Case/Controller/Component/BcReplacePrefixComponentTest.php
Labels: Todo

#1405 fix #1404 URLのクエリがセッションに保存されない問題を解決
  lib/Baser/Lib/BcSite.php
Labels: Bug
