Repository baserproject/basercms, pull requests merged in 2020-04, with the labels that each got.

#1409 外部からユーザをログイン不能にされる脆弱性の暫定対応
  lib/Baser/Controller/UsersController.php
Labels: Todo

#1283 fix #1282 ウィジェット内ブログタグ一覧で表示するタグのリンク先がNotFoundになるため
  lib/Baser/Plugin/Blog/View/Elements/blog_tag_list.php
Labels: Bug

#1414 fix #1411 ブログの一覧に表示する件数について100件以内となるようバリデーションを追加
  lib/Baser/Plugin/Blog/Model/BlogContent.php
  lib/Baser/Plugin/Blog/View/BlogContents/admin/form.php
Labels: Todo

#1396 fix #1012 アイキャッチ画像登録時にファイルサイズのエラーメッセージ追加
  lib/Baser/Model/BcAppModel.php
  lib/Baser/Model/Behavior/BcUploadBehavior.php
  lib/Baser/Plugin/Blog/Model/BlogPost.php
  lib/Baser/Plugin/Mail/Model/MailMessage.php
  lib/Baser/Plugin/Mail/View/Helper/MailformHelper.php
  lib/Baser/Test/Case/Model/BcAppTest.php
Labels: Review

#1419 #1012 ブログ記事以外のアイキャッチ画像登録時にファイルサイズのエラーメッセージ追加
  lib/Baser/Model/Behavior/BcUploadBehavior.php
  lib/Baser/Model/Content.php
Labels: Todo

#1431 #1430 Windows版SQLiteの対応バージョンをconfig化する
  lib/Baser/Config/setting.php
  lib/Baser/Controller/InstallationsController.php
Labels: Todo

#1426 fix #1425 コンテンツ管理：同階層に移動した場合、サブサイトの同階層に同名コンテンツが存在するとエラーとなる問題を改善
  lib/Baser/Model/Content.php
Labels: Bug

#1417 fix #1011 ファイルアップロード時にpost_max_size超過のエラーメッセージ追加
  lib/Baser/Controller/ContentFoldersController.php
  lib/Baser/Controller/ContentLinksController.php
  lib/Baser/Controller/ContentsController.php
  lib/Baser/Controller/EditorTemplatesController.php
  lib/Baser/Controller/PagesController.php
  lib/Baser/Controller/PluginsController.php
  lib/Baser/Controller/ThemeConfigsController.php
  lib/Baser/Controller/ThemeFilesController.php
  lib/Baser/Controller/ThemesController.php
  lib/Baser/Controller/ToolsController.php
  lib/Baser/Locale/baser.pot
  lib/Baser/Locale/eng/LC_MESSAGES/baser.po
  lib/Baser/Model/BcAppModel.php
  lib/Baser/Plugin/Blog/Controller/BlogContentsController.php
  lib/Baser/Plugin/Blog/Controller/BlogPostsController.php
  lib/Baser/Plugin/Mail/Controller/MailContentsController.php
  lib/Baser/Plugin/Uploader/Controller/UploaderFilesController.php
Labels: Todo
