Repository baserproject/basercms, pull requests merged in 2021-01, with the labels that each got.

#1592 fix #1591 adminthirdを使用している場合、 システム管理グループに属していないユーザーで、固定ページのプレビュー時、co…
  app/webroot/theme/admin-third/Pages/admin/form.php
Labels: Bug

#1608 fix #1607 admin-third利用時「最近の動き」の表示テキストが折り返して表示されない点を修正
  app/webroot/theme/admin-third/__assets/css/components/_update-log.scss
  app/webroot/theme/admin-third/css/admin/style.css
Labels: Todo

#1610 fix : #1609 BlogHelper::getPostContentで、文字数をカットした際に最後に「・・・」等の文字列を挿入できるよう修正
  lib/Baser/Plugin/Blog/View/Helper/BlogHelper.php
Labels: Todo

#1617 fix #1616 削除した（ゴミ箱に入れた）メールフォームの設定画面や受信一覧が閲覧できる
  lib/Baser/Plugin/Mail/Controller/MailMessagesController.php
Labels: Bug

#1627 BcBaserHelper::crumbs() で onSchema が true の時、ソースの改行に起因する空白が入るのを回避
  lib/Baser/View/Elements/crumbs.php
  lib/Baser/View/Helper/BcBaserHelper.php
Labels: Todo

#1631 fix #1629 メールフォーム emailチェックで、全角文字がバリデーションを通過してしまう問題を解決
  lib/Baser/Plugin/Mail/Model/MailMessage.php
Labels: Bug

#1604 fix #1603 ブログコンテンツ、メールコンテンツのデータキャッシュが無限に生成されてしまう問題を修正
  lib/Baser/Plugin/Blog/Config/setting.php
  lib/Baser/Plugin/Mail/Config/setting.php
Labels: Bug, Reviewed

#1619 fix #1596 ブログ記事noが重複して保存される問題を改善
  lib/Baser/Plugin/Blog/Config/Schema/blog_posts.php
  lib/Baser/Plugin/Blog/Controller/BlogPostsController.php
  lib/Baser/Plugin/Blog/Model/BlogPost.php
  lib/Baser/Plugin/Blog/Test/Case/Model/BlogContentTest.php
  lib/Baser/Plugin/Blog/Test/Case/Model/BlogPostTest.php
  lib/Baser/Plugin/Blog/Test/Case/View/Helper/BlogHelperTest.php
  lib/Baser/Plugin/Blog/Test/Fixture/Model/BlogPost/BlogCategoryModelFixture.php
  lib/Baser/Plugin/Blog/Test/Fixture/Model/BlogPost/BlogPostModelFixture.php
  lib/Baser/Plugin/Blog/Test/Fixture/Model/BlogTag/BlogPostBlogTagFindCustomPramsFixture.php
  lib/Baser/Plugin/Blog/Test/Fixture/View/Helper/BlogBaserHelper/BlogPostBlogBaserHelperFixture.php
  lib/Baser/Test/Fixture/Default/BlogPostFixture.php
Labels: Bug
