Repository baserproject/basercms, pull requests merged in 2021-03, with the labels that each got.

#1657 fix #1656 テーマ用初期データダウンロード時のメモリー制限を無効にする
  lib/Baser/Controller/ThemesController.php
Labels: Todo

#1652 fix #1651 セッションメッセージの表示テキストが折り返して表示されないため修正
  app/webroot/theme/admin-third/__assets/css/components/_notification.scss
  app/webroot/theme/admin-third/css/admin/style.css
  lib/Baser/Controller/PagesController.php
Labels: Review, Reviewed, Todo

#1634 公開期間を利用しているBlogContent,BlogPostモデルにてキャッシュを利用しないよう変更
  lib/Baser/Plugin/Blog/Config/setting.php
  lib/Baser/Plugin/Blog/Controller/BlogController.php
  lib/Baser/Plugin/Blog/Model/BlogContent.php
  lib/Baser/Plugin/Blog/Model/BlogPost.php
  lib/Baser/Plugin/Blog/View/Helper/BlogHelper.php
Labels: Bug, Reviewed
