Repository baserproject/basercms, pull requests merged in 2023-06, with the labels that each got.

#2226 fix #2003 BcDatabaseService::checkDbConnection のユニットテスト実装
  plugins/baser-core/src/Service/BcDatabaseService.php
  plugins/baser-core/tests/TestCase/Service/BcDatabaseServiceTest.php
Labels: ver5

#2246 fix #2002 BcDatabaseService::testConnectDb のユニットテスト実装
  plugins/baser-core/src/Service/BcDatabaseService.php
  plugins/baser-core/tests/TestCase/Service/BcDatabaseServiceTest.php
Labels: ver5

#2262 fix #2255 EditorTemplatesService::getList のユニットテスト実装
  plugins/bc-editor-template/src/Service/EditorTemplatesService.php
  plugins/bc-editor-template/tests/TestCase/Service/EditorTemplatesServiceTest.php
Labels: ver5

#2261 fix #2254 EditorTemplatesService::getNew のユニットテスト実装
  plugins/bc-editor-template/src/Service/EditorTemplatesService.php
  plugins/bc-editor-template/tests/TestCase/Service/EditorTemplatesServiceTest.php
Labels: ver5

#2263 fix #2256 EditorTemplatesService::delete のユニットテスト実装
  plugins/bc-editor-template/src/Service/EditorTemplatesService.php
  plugins/bc-editor-template/tests/TestCase/Service/EditorTemplatesServiceTest.php
Labels: ver5

#2242 fix #2220 blog tags service create unit test
  plugins/bc-blog/src/Service/BlogTagsService.php
  plugins/bc-blog/tests/TestCase/Service/BlogTagsServiceTest.php
Labels: Reviewed

#2264 fix #2237 MailFieldsService::batch のユニットテストを実装
  plugins/bc-mail/src/Service/MailFieldsService.php
  plugins/bc-mail/tests/TestCase/Service/MailFieldsServiceTest.php
Labels: Reviewed

#2272 fix #2257 EditorTemplatesService::update のユニットテスト実装
  plugins/bc-editor-template/src/Service/EditorTemplatesService.php
  plugins/bc-editor-template/tests/TestCase/Service/EditorTemplatesServiceTest.php
Labels: Reviewed

#2292 fix #2290 #2291 MailContentsAdminService Unit Test
  plugins/bc-mail/src/Service/Admin/MailContentsAdminService.php
  plugins/bc-mail/tests/TestCase/Service/Admin/MailContentsAdminServiceTest.php
Labels: Reviewed

#2312 fix #2294 MailFieldsAdminService::getViewVarsForEdit のユニットテストを実装
  plugins/bc-mail/tests/TestCase/Service/Admin/MailFieldsAdminServiceTest.php
Labels: Reviewed

#2356 fix #2233 MailFieldsService::copy のユニットテストを実装 #2233
  plugins/bc-mail/src/Service/MailFieldsService.php
  plugins/bc-mail/tests/Scenario/MailFieldsScenario.php
  plugins/bc-mail/tests/TestCase/Service/MailFieldsServiceTest.php
Labels: Reviewed

#2365 fix #2326 MailFrontService::getEditLink のユニットテストを実装
  plugins/bc-mail/src/Service/Front/MailFrontService.php
  plugins/bc-mail/tests/TestCase/Service/Front/MailFrontServiceTest.php
Labels: Reviewed

#2366 fix #2327 MailFrontService::createMailData のユニットテストを実装
  plugins/bc-mail/src/Service/Front/MailFrontService.php
  plugins/bc-mail/tests/TestCase/Service/Front/MailFrontServiceTest.php
Labels: Reviewed

#2470 fix #2458 CustomContentsService::getControlSource のユニットテストを実装
  plugins/bc-custom-content/src/Service/CustomContentsService.php
  plugins/bc-custom-content/tests/Scenario/CustomTablesScenario.php
  plugins/bc-custom-content/tests/TestCase/Service/CustomContentsServiceTest.php
Labels: Reviewed

#2471 fix #2425 CustomEntriesService::getFieldControlTypeのユニットテストを実装
  plugins/bc-custom-content/src/Service/CustomEntriesService.php
  plugins/bc-custom-content/tests/TestCase/Service/CustomEntriesServiceTest.php
Labels: Reviewed

#2482 Test CustomEntriesService delete
  plugins/bc-custom-content/src/Service/CustomEntriesService.php
  plugins/bc-custom-content/tests/TestCase/Service/CustomEntriesServiceTest.php
Labels: Reviewed

#2492 fix 4系版のアップロードファイル一覧で表示件数リンクが正しく機能しない動作を修正
  lib/Baser/Plugin/Uploader/webroot/js/admin/uploader_files/uploader_list.js
Labels: Reviewed

#2501 CustomEntriesServiceTest test_getControlSource
  plugins/bc-custom-content/src/Service/CustomEntriesService.php
  plugins/bc-custom-content/tests/TestCase/Service/CustomEntriesServiceTest.php
Labels: Reviewed

#2508 CustomEntriesServiceTest test_isAllowPublish
  plugins/bc-custom-content/src/Service/CustomEntriesService.php
  plugins/bc-custom-content/tests/TestCase/Service/CustomEntriesServiceTest.php
Labels: Reviewed

#2509 CustomEntriesServiceTest test_getUrl
  plugins/bc-custom-content/src/Service/CustomEntriesService.php
  plugins/bc-custom-content/tests/TestCase/Service/CustomEntriesServiceTest.php
Labels: Reviewed

#2407 fix #2406 [ver4] /tags/{存在しないタグ名} がステータス200として戻される問題を解決
  lib/Baser/Plugin/Blog/Controller/BlogController.php
Labels: Bug, ver4

#2178 fix #2177 PHP5.4に対応していない問題を解決 [ver4]
  lib/Baser/Lib/Error/BcErrorHandler.php
Labels: ver4

#2174 fix #2173 [コンテンツ]同一階層にindexがなくてもindex_1があるとindexが作成できない問題を解決
  lib/Baser/Model/Content.php
Labels: Bug, ver4
