Repository baserproject/basercms, pull requests merged in 2023-05, with the labels that each got.

#2105 fix #2104 ThemeConfigsTable::initialize のユニットテスト実装
  plugins/bc-theme-config/src/Model/Table/ThemeConfigsTable.php
  plugins/bc-theme-config/tests/TestCase/Model/Table/ThemeConfigTest.php
Labels: Reviewed, ver5

#2126 fix #2114 ThemeFoldersService::getForm
  plugins/bc-theme-file/src/Service/ThemeFoldersService.php
  plugins/bc-theme-file/tests/TestCase/Service/ThemeFoldersServiceTest.php
Labels: ver5

#2127 fix #2115 ThemeFoldersService::get のユニットテスト実装
  plugins/bc-theme-file/src/Service/ThemeFoldersService.php
  plugins/bc-theme-file/tests/TestCase/Service/ThemeFoldersServiceTest.php
Labels: ver5

#2131 fix #2117 ThemeFoldersService::create のユニットテスト実装
  plugins/bc-theme-file/src/Service/ThemeFoldersService.php
  plugins/bc-theme-file/tests/TestCase/Service/ThemeFoldersServiceTest.php
Labels: ver5

#2129 fix #2116 ThemeFoldersService::getIndex のユニットテスト実装
  plugins/baser-core/src/TestSuite/BcTestCase.php
  plugins/bc-theme-file/src/Service/ThemeFoldersService.php
  plugins/bc-theme-file/tests/TestCase/Service/ThemeFoldersServiceTest.php
Labels: Reviewed, ver5

#2132 fix #2123 ThemeFoldersService::batch のユニットテスト実装
  plugins/bc-theme-file/src/Service/ThemeFoldersService.php
  plugins/bc-theme-file/tests/TestCase/Service/ThemeFoldersServiceTest.php
Labels: ver5

#2133 fix #2107 #1965 #2108 #2111 #2109 MailContentsService Unit Test
  plugins/bc-mail/src/Service/MailContentsService.php
  plugins/bc-mail/tests/Scenario/MailContentsScenario.php
  plugins/bc-mail/tests/TestCase/Service/MailContentsServiceTest.php
Labels: ver5

#2136 fix #2120 ThemeFoldersService::copy のユニットテスト実装
  plugins/bc-theme-file/src/Service/ThemeFoldersService.php
  plugins/bc-theme-file/tests/TestCase/Service/ThemeFoldersServiceTest.php
Labels: ver5

#2139 fix #1938 BcUtil::loginUser 引数削除
  plugins/baser-core/src/Service/UsersService.php
  plugins/baser-core/src/Utility/BcUtil.php
Labels: ver5

#2141 fix #2122 ThemeFoldersService::getNamesByFullpath のユニットテスト実装
  plugins/bc-theme-file/src/Service/ThemeFoldersService.php
  plugins/bc-theme-file/tests/TestCase/Service/ThemeFoldersServiceTest.php
Labels: ver5

#2142 fix #2121 ThemeFoldersService::copyToTheme のユニットテスト実装
  plugins/bc-theme-file/src/Service/ThemeFoldersService.php
  plugins/bc-theme-file/tests/TestCase/Service/ThemeFoldersServiceTest.php
Labels: ver5

#2143 fix #2103 ThemeConfigsTable::validationDefault のユニットテスト実装
  plugins/bc-theme-config/src/Model/Table/ThemeConfigsTable.php
  plugins/bc-theme-config/tests/TestCase/Model/Table/ThemeConfigTest.php
Labels: ver5

#2137 ajaxのheader削除
  plugins/bc-admin-third/src/bc_blog/js/admin/blog_posts/form.js
  plugins/bc-admin-third/src/bc_search_index/js/admin/search_indexes/index.js
  plugins/bc-admin-third/src/bc_uploader/js/admin/uploader_files/index_panel.js
  plugins/bc-admin-third/src/bc_widget_area/js/admin/widget_areas/form.js
  plugins/bc-admin-third/src/js/admin/_lib/jquery.bcBatch.js
  plugins/bc-admin-third/src/js/admin/_lib/jquery.bcSortable.js
  plugins/bc-admin-third/src/js/admin/_lib/jquery.bcTree.js
  plugins/bc-admin-third/src/js/admin/contents/edit.js
  plugins/bc-admin-third/src/js/admin/permissions/dialog.js
  plugins/bc-admin-third/src/js/admin/site_configs/index.js
  plugins/bc-admin-third/webroot/bc_blog/js/admin/blog_posts/form.bundle.js
  plugins/bc-admin-third/webroot/bc_blog/js/admin/blog_posts/form.bundle.js.map
  plugins/bc-admin-third/webroot/bc_search_index/js/admin/search_indexes/index.bundle.js
  plugins/bc-admin-third/webroot/bc_search_index/js/admin/search_indexes/index.bundle.js.map
  plugins/bc-admin-third/webroot/bc_uploader/js/admin/uploader_files/index_panel.bundle.js
  plugins/bc-admin-third/webroot/bc_uploader/js/admin/uploader_files/index_panel.bundle.js.map
  plugins/bc-admin-third/webroot/bc_widget_area/js/admin/widget_areas/form.bundle.js
  plugins/bc-admin-third/webroot/bc_widget_area/js/admin/widget_areas/form.bundle.js.map
  plugins/bc-admin-third/webroot/js/admin/common.bundle.js
  plugins/bc-admin-third/webroot/js/admin/common.bundle.js.map
  plugins/bc-admin-third/webroot/js/admin/contents/edit.bundle.js
  plugins/bc-admin-third/webroot/js/admin/contents/edit.bundle.js.map
  plugins/bc-admin-third/webroot/js/admin/permissions/dialog.bundle.js
  plugins/bc-admin-third/webroot/js/admin/permissions/dialog.bundle.js.map
  plugins/bc-admin-third/webroot/js/admin/site_configs/index.bundle.js
  plugins/bc-admin-third/webroot/js/admin/site_configs/index.bundle.js.map
Labels: ver5

#2138 fix #1928 expectExceptionを使用したテストの修正
  plugins/baser-core/tests/TestCase/Service/ContentsServiceTest.php
  plugins/bc-favorite/tests/TestCase/Service/FavoritesServiceTest.php
Labels: ver5

#2165 fix #2010 BlogPostsTable::validationDefault のユニットテスト実装
  plugins/bc-blog/src/Model/Table/BlogPostsTable.php
  plugins/bc-blog/tests/TestCase/Model/BlogPostsTableTest.php
Labels: ver5

#2168 fix #2004 BlogPostsTable::allowPublish のユニットテスト実装
  plugins/bc-blog/src/Model/Table/BlogPostsTable.php
Labels: ver5

#2172 fix #2171 BlogPostsTable::copy のユニットテスト実装
  plugins/bc-blog/src/Model/Table/BlogPostsTable.php
  plugins/bc-blog/tests/TestCase/Model/BlogPostsTableTest.php
Labels: ver5

#2176 fix #2175 BlogPostsTable::_getEntryDatesConditions のユニットテスト実装
  plugins/bc-blog/src/Model/Table/BlogPostsTable.php
  plugins/bc-blog/tests/TestCase/Model/BlogPostsTableTest.php
Labels: ver5

#2181 fix #2171 BlogPostsTable::getEntryDates のユニットテスト実装
  plugins/bc-blog/src/Model/Table/BlogPostsTable.php
  plugins/bc-blog/tests/Scenario/MultiSiteBlogPostScenario.php
  plugins/bc-blog/tests/TestCase/Model/BlogPostsTableTest.php
Labels: ver5

#2183 fix #2015 BlogPostsAdminService::getPublishLink のユニットテスト実装
  plugins/bc-blog/src/Service/Admin/BlogPostsAdminService.php
  plugins/bc-blog/tests/Scenario/BlogPostsAdminServiceScenario.php
  plugins/bc-blog/tests/TestCase/Service/Admin/BlogPostsAdminServiceTest.php
Labels: Reviewed, ver5

#2190 fix #1930 FrozenTime::setToStringFormat 書式変更
  plugins/baser-core/src/Model/Table/AppTable.php
  plugins/baser-core/tests/TestCase/Model/Table/AppTableTest.php
  plugins/baser-core/tests/TestCase/Model/Table/ContentsTableTest.php
Labels: Review

#2185 fix #2016 BlogPostsAdminService::getEditorOptions のユニットテスト実装
  plugins/bc-blog/src/Service/Admin/BlogPostsAdminService.php
  plugins/bc-blog/tests/TestCase/Service/Admin/BlogPostsAdminServiceTest.php
Labels: ver5

#2188 fix #2186 EditorTemplatesTable::initialize のユニットテスト実装
  plugins/bc-editor-template/src/Model/Table/EditorTemplatesTable.php
  plugins/bc-editor-template/tests/TestCase/Model/Table/EditorTemplateTest.php
  plugins/bc-editor-template/tests/TestCase/Model/Table/EditorTemplatesTableTest.php
Labels: ver5

#2193 fix #2192 UploaderFilesTable::initialize のユニットテスト実装
  plugins/baser-core/src/TestSuite/BcTestCase.php
  plugins/bc-uploader/src/Model/Table/UploaderFilesTable.php
  plugins/bc-uploader/tests/TestCase/Model/Table/UploaderFilesTableTest.php
Labels: ver5

#2201 fix #2200 UploaderConfigsTable::initialize のユニットテスト実装
  plugins/bc-uploader/src/Model/Table/UploaderConfigsTable.php
  plugins/bc-uploader/tests/TestCase/Model/Table/UploaderConfigsTableTest.php
Labels: ver5

#2223 fix #2001 BcDatabaseService::constructionTable のユニットテストを実装
  plugins/baser-core/src/Service/BcDatabaseService.php
  plugins/baser-core/tests/TestCase/Service/BcDatabaseServiceTest.php
Labels: ver5

#2184 fix #2144 #2145 #2147 #2148 MailMessagesTable Unit test
  plugins/bc-mail/src/Model/Table/MailMessagesTable.php
  plugins/bc-mail/tests/TestCase/Model/MailMessagesTableTest.php
Labels: Reviewed

#2194 fix #2187 EditorTemplatesTable::validationDefault のユニットテスト実装
  plugins/bc-editor-template/src/Model/Table/EditorTemplatesTable.php
  plugins/bc-editor-template/tests/TestCase/Model/Table/EditorTemplatesTableTest.php
Labels: ver5

#2196 fix #2195 UploaderCategoriesTable::initialize のユニットテスト実装
  plugins/bc-uploader/src/Model/Table/UploaderCategoriesTable.php
  plugins/bc-uploader/tests/TestCase/Model/Table/UploaderCategoriesTableTest.php
Labels: ver5

#2198 【カスタムコンテンツ】フィールドを追加する際にデフォルトでAPIへの出力を有効にする fix #2197
  plugins/bc-admin-third/src/bc_custom_content/js/admin/custom_tables/form.js
  plugins/bc-admin-third/templates/plugin/BcCustomContent/Admin/element/CustomTables/available_field.php
  plugins/bc-admin-third/webroot/bc_custom_content/js/admin/custom_tables/form.bundle.js
  plugins/bc-admin-third/webroot/bc_custom_content/js/admin/custom_tables/form.bundle.js.map
Labels: ver5

#2202 fix #2005 BlogTagsTable::hasNewTagAddablePermission のユニットテスト実装
  plugins/bc-blog/src/Model/Table/BlogTagsTable.php
  plugins/bc-blog/tests/TestCase/Model/BlogTagsTableTest.php
Labels: ver5

#2204 fix #2203 MailFieldsTable::initialize のユニットテストを実装
  plugins/bc-mail/src/Model/Table/MailFieldsTable.php
  plugins/bc-mail/tests/TestCase/Model/Table/MailFieldsTableTest.php
Labels: ver5

#2208 fix #2207 UploaderCategoriesTable::validationDefault のユニットテスト
  plugins/bc-uploader/src/Model/Table/UploaderCategoriesTable.php
  plugins/bc-uploader/tests/TestCase/Model/Table/UploaderCategoriesTableTest.php
Labels: ver5

#2211 fix #1962 BcDatabaseService::renameColumn のユニットテストを実装
  plugins/baser-core/src/Service/BcDatabaseService.php
  plugins/baser-core/tests/TestCase/Service/BcDatabaseServiceTest.php
Labels: ver5

#2222 fix #1967 BcDatabaseService::initAdapter のユニットテストを実装
  plugins/baser-core/src/Service/BcDatabaseService.php
  plugins/baser-core/tests/TestCase/Service/BcDatabaseServiceTest.php
Labels: ver5

#2210 fix #2209 UploaderCategoriesTable::copy のユニットテスト実装
  plugins/bc-uploader/src/Model/Table/UploaderCategoriesTable.php
  plugins/bc-uploader/tests/TestCase/Model/Table/UploaderCategoriesTableTest.php
Labels: ver5

#2221 fix #2149 #2150 #2151 #2152 #2153 #2154 #2155 #2156 #2157 #2158 #2159 #2160 #2161 #2162 #2163 #2164 MailMessagesService unit test
  plugins/baser-core/src/Utility/BcUtil.php
  plugins/bc-mail/src/Service/MailMessagesService.php
  plugins/bc-mail/tests/Factory/MailMessagesFactory.php
  plugins/bc-mail/tests/Fixture/Factory/MailMessagesFixture.php
  plugins/bc-mail/tests/Scenario/MailContentsScenario.php
  plugins/bc-mail/tests/TestCase/Service/MailMessagesServiceTest.php
Labels: Reviewed, ver5

#2244 [システム]USE_CORE_APIがtrueでない場合にJWT認証が使用できない fix #2205
  plugins/baser-core/src/Plugin.php
Labels: Bug
