Repository baserproject/basercms, pull requests merged in 2023-08, with the labels that each got.

#2636 ThemeFilesService::upload ユニットテストを実装
  plugins/bc-theme-file/src/Service/ThemeFilesService.php
  plugins/bc-theme-file/tests/TestCase/Service/ThemeFilesServiceTest.php
Labels: Reviewed

#2659 ContentLinksTable::copy のユニットテスト実装
  plugins/bc-content-link/src/Model/Table/ContentLinksTable.php
  plugins/bc-content-link/tests/TestCase/Model/Table/ContentLinksTableTest.php
Labels: Reviewed

#2661 test-admin-BlogContentsController-edit
  plugins/bc-blog/src/Controller/Admin/BlogContentsController.php
  plugins/bc-blog/tests/TestCase/Controller/Admin/BlogContentsControllerTest.php
Labels: Reviewed

#2682 fix #2630 【システム】ログアウトしても代理ログイン情報が記録されたまま
  plugins/baser-core/src/Controller/Admin/UsersController.php
Labels: Reviewed

#2708 Test blog controller ajax add comment
  plugins/bc-blog/src/Controller/BlogController.php
  plugins/bc-blog/tests/TestCase/Controller/BlogControllerTest.php
Labels: Reviewed

#2689 fix #2678 【システム】管理画面「パスワードを忘れた場合はこちら」存在するメールアドレスと存在しないメールアドレスを入力した場合とで挙動が異なる
  plugins/baser-core/src/Controller/Admin/PasswordRequestsController.php
Labels: Reviewed

#2639 fix #2638 baserCMS4系　php８でビューキャッシュが生成されない問題を解決
  lib/Baser/Controller/Component/BcContentsComponent.php
Labels: ver4

#2571 fix #2570 4系版メールフォームで1フォーム内で複数のファイルタイプを利用すると送信完了前にエラーが起こる動作を改善
  lib/Baser/Lib/BcFileUploader.php
Labels: Bug, ver4

#2538 bccolumテーマのグローバルメニューの挙動に関する不具合解消
  lib/Baser/View/Helper/BcBaserHelper.php
Labels: Bug, ver4
