Repository baserproject/basercms, pull requests merged in 2023-10, with the labels that each got.

#2784 fix #2783 CGIモードでJWT認証が可能になるようにしたい
  plugins/baser-core/src/Middleware/BcRequestFilterMiddleware.php
  plugins/baser-core/src/Plugin.php
  plugins/baser-core/tests/TestCase/PluginTest.php
Labels: Reviewed

#2778 2773-basics
  __assets/plugins/baser-core/src/basics.php
  __assets/plugins/baser-core/tests/TestCase/BcBasicsTest.php
Labels: Reviewed

#2779 fix #1903 コンテンツ一覧（表）コピーの際にコピー先のタイトルに「のコピー」とつかない
  plugins/baser-core/src/Model/Table/ContentFoldersTable.php
  plugins/baser-core/src/Model/Table/PagesTable.php
  plugins/bc-admin-third/src/js/admin/_lib/jquery.bcTree.js
  plugins/bc-admin-third/templates/Admin/element/Contents/index_row_table.php
  plugins/bc-admin-third/templates/Admin/element/Contents/index_setup_tree.php
  plugins/bc-blog/src/Model/Table/BlogContentsTable.php
  plugins/bc-content-link/src/Model/Table/ContentLinksTable.php
  plugins/bc-mail/src/Model/Table/MailContentsTable.php
Labels: Reviewed

#2780 BcBaserHelperTest
  plugins/baser-core/src/Utility/BcFile.php
  plugins/baser-core/tests/TestCase/Utility/BcFileTest.php
  plugins/baser-core/tests/TestCase/View/Helper/BcBaserHelperTest.php
Labels: Reviewed

#2495 BcUpload 同一モデルの複数保存に対応
  plugins/baser-core/src/Model/Behavior/BcUploadBehavior.php
  plugins/baser-core/src/Utility/BcFileUploader.php
  plugins/baser-core/tests/TestCase/Model/Behavior/BcUploadBehaviorTest.php
  plugins/baser-core/tests/TestCase/Utility/BcFileUploaderTest.php
Labels: Adjusting

#2791 Admin/ThemeFilesController::beforeRender のユニットテスト
  plugins/bc-theme-file/src/Controller/Admin/ThemeFilesController.php
  plugins/bc-theme-file/tests/TestCase/Controller/Admin/ThemeFilesControllerTest.php
Labels: Reviewed

#2793 Admin/ThemeFilesController::index のユニットテスト
  plugins/bc-theme-file/src/Controller/Admin/ThemeFilesController.php
  plugins/bc-theme-file/tests/TestCase/Controller/Admin/ThemeFilesControllerTest.php
Labels: Reviewed

#2796 Admin/ThemeFilesController::add のユニットテスト
  plugins/bc-theme-file/src/Controller/Admin/ThemeFilesController.php
  plugins/bc-theme-file/tests/TestCase/Controller/Admin/ThemeFilesControllerTest.php
Labels: Reviewed

#2707 fix #2706 [メールフォーム]4系版メールフォームで、フィールドタイプがカレンダーで任意入力、拡張入力チェックに「日付チェック」を…
  lib/Baser/Plugin/Mail/Model/MailMessage.php
Labels: ver4

#2797 Dev #2773 bc plugin
  plugins/baser-core/src/BcPlugin.php
  plugins/baser-core/src/Utility/BcFolder.php
  plugins/baser-core/tests/TestCase/BcPluginTest.php
  plugins/baser-core/tests/TestCase/Utility/BcFolderTest.php
Labels: Reviewed

#2798 fix #1901 【メールフォーム】バリデーションエラー時にチェックボックスのチェックが外れる #1901
  plugins/bc-mail/src/Service/Front/MailFrontService.php
Labels: Reviewed
