Repository baserproject/basercms, pull requests merged in 2023-04, with the labels that each got.

#2045 「コンテンツリンクの編集前・編集後」のイベントを追加
  plugins/bc-content-link/src/Controller/Admin/ContentLinksController.php
  plugins/bc-content-link/tests/TestCase/Controller/Admin/ContentLinksControllerTest.php
Labels: ver5

#2050 fix Users.beforeEdit
  plugins/baser-core/src/Controller/Admin/UsersController.php
  plugins/baser-core/tests/TestCase/Controller/Admin/UsersControllerTest.php
Labels: ver5

#2052 「カスタムテーブルの登録前・登録後・編集前・編集後」のイベントを追加
  plugins/bc-custom-content/src/Controller/Admin/CustomTablesController.php
  plugins/bc-custom-content/tests/TestCase/Controller/Admin/CustomTablesControllerTest.php
Labels: ver5

#2053 「カスタムエントリーの検索時・登録前・登録後・編集前・編集後」のイベントを追加
  plugins/bc-custom-content/src/Controller/Admin/CustomEntriesController.php
  plugins/bc-custom-content/tests/TestCase/Controller/Admin/CustomEntriesControllerTest.php
Labels: Reviewed, ver5

#2044 「エディターテンプレートの登録前・編集後」のイベントを追加
  plugins/bc-editor-template/src/Controller/Admin/EditorTemplatesController.php
  plugins/bc-editor-template/tests/TestCase/Controller/Admin/EditorTemplatesControllerTest.php
Labels: Reviewed, ver5

#2055 「メールコンテンツの編集前・編集後」のイベントを追加
  plugins/bc-mail/src/Controller/Admin/MailContentsController.php
  plugins/bc-mail/tests/Scenario/MailContentsScenario.php
  plugins/bc-mail/tests/TestCase/Controller/Admin/MailContentsControllerTest.php
Labels: Reviewed, ver5

#2054 fix BlogCategoriesController Event test
  plugins/bc-blog/src/Controller/Admin/BlogCategoriesController.php
  plugins/bc-blog/tests/TestCase/Controller/Admin/BlogCategoriesControllerTest.php
Labels: Reviewed

#2056 「メールフィールドの登録前・登録後・編集前・編集後」のイベントを追加
  plugins/bc-mail/src/Controller/Admin/MailFieldsController.php
  plugins/bc-mail/tests/TestCase/Controller/Admin/MailFieldsControllerTest.php
Labels: Reviewed, ver5

#1900 fix #1899 php8系で$this->BcBaser->crumbs()を使用するとWarningがでる問題を解決
  lib/Baser/View/Helper/BcBaserHelper.php
Labels: ver4

#2077 fix #2074 Api/MailFieldsController::batch のユニットテストを実装
  plugins/bc-mail/src/Controller/Api/Admin/MailFieldsController.php
  plugins/bc-mail/tests/TestCase/Controller/Api/Admin/MailFieldsControllerTest.php
Labels: ver5

#2078 fix #2074 Api/MailFieldsController::update_sort のユニットテストを実装
  plugins/bc-mail/src/Controller/Api/Admin/MailFieldsController.php
  plugins/bc-mail/tests/TestCase/Controller/Api/Admin/MailFieldsControllerTest.php
Labels: ver5

#2085 fix #1963 Api/WidgetAreasController::batch のユニットテスト実装
  plugins/bc-widget-area/src/Controller/Api/Admin/WidgetAreasController.php
  plugins/bc-widget-area/tests/TestCase/Controller/Api/Admin/WidgetAreasControllerTest.php
Labels: ver5

#2086 fix #1974 Api/MailContentsController::add のユニットテスト実装
  plugins/bc-mail/src/Controller/Api/Admin/MailContentsController.php
  plugins/bc-mail/tests/TestCase/Controller/Api/Admin/MailContentsControllerTest.php
Labels: ver5

#2087 fix #1972 Api/MailContentsController::copy のユニットテスト実装
  plugins/bc-mail/src/Controller/Api/Admin/MailContentsController.php
  plugins/bc-mail/tests/TestCase/Controller/Api/Admin/MailContentsControllerTest.php
Labels: ver5

#2057 「ブログタグのコピー前・コピー後」のイベントを追加
  plugins/bc-blog/src/Model/Table/BlogTagsTable.php
  plugins/bc-blog/tests/TestCase/Model/BlogTagsTableTest.php
Labels: Reviewed, ver5

#2058 「ブログカテゴリのコピー前・コピー後」のイベントを追加
  plugins/bc-blog/src/Model/Table/BlogCategoriesTable.php
  plugins/bc-blog/tests/TestCase/Model/BlogCategoriesTableTest.php
Labels: Reviewed, ver5

#2059 「コンテンツリンクのコピー前・コピー後」のイベントを追加
  plugins/bc-content-link/src/Model/Table/ContentLinksTable.php
  plugins/bc-content-link/tests/TestCase/Model/Table/ContentLinksTableTest.php
Labels: Reviewed, ver5

#2060 「コンテンツフォルダーのコピー前・コピー後」のイベントを追加
  plugins/baser-core/src/Model/Table/ContentFoldersTable.php
  plugins/baser-core/tests/TestCase/Model/Table/ContentFoldersTableTest.php
Labels: Reviewed, ver5

#2062 #1939 blog contents controller event test
  plugins/bc-blog/src/Controller/Admin/BlogContentsController.php
  plugins/bc-blog/tests/TestCase/Controller/Admin/BlogContentsControllerTest.php
Labels: Reviewed, ver5

#2064 「ブログタグの登録前・登録後・編集前・編集後」のイベントを追加
  plugins/bc-blog/src/Controller/Admin/BlogTagsController.php
  plugins/bc-blog/tests/TestCase/Controller/Admin/BlogTagsControllerTest.php
Labels: Reviewed, ver5

#2071 fix #1948 #1949 #1950 #1951 in mail message validation test
  __assets/plugins/baser-core/src/basics.php
  plugins/baser-core/src/Utility/BcUtil.php
  plugins/bc-mail/src/Model/Validation/MailMessageValidation.php
  plugins/bc-mail/tests/TestCase/Model/Validation/MailMessageValidationTest.php
Labels: Reviewed, ver5

#2065 fix #1946 PermissionGroupsController::rebuild_by_user_group のユニットテスト実装
  plugins/baser-core/src/Controller/Admin/PermissionGroupsController.php
  plugins/baser-core/tests/TestCase/Controller/Admin/PermissionGroupsControllerTest.php
Labels: Reviewed, ver5

#2067 fix #2066 PermissionGroupsController::edit のユニットテスト実装
  plugins/baser-core/src/Controller/Admin/PermissionGroupsController.php
  plugins/baser-core/tests/TestCase/Controller/Admin/PermissionGroupsControllerTest.php
Labels: Reviewed, ver5

#2069 fix #2068 PermissionGroupsController::index のユニットテスト実装
  plugins/baser-core/src/Controller/Admin/PermissionGroupsController.php
  plugins/baser-core/tests/TestCase/Controller/Admin/PermissionGroupsControllerTest.php
Labels: Reviewed, ver5

#2072 fix #2032 Admin/BlogPostsController::beforeFilter のユニットテスト実装
  plugins/bc-blog/src/Controller/Admin/BlogPostsController.php
  plugins/bc-blog/tests/TestCase/Controller/Admin/BlogPostsControllerTest.php
Labels: Reviewed, ver5

#2075 fix #2073 PermissionGroupsController::addのユニットテスト実装
  plugins/baser-core/src/Controller/Admin/PermissionGroupsController.php
  plugins/baser-core/tests/TestCase/Controller/Admin/PermissionGroupsControllerTest.php
Labels: Reviewed, ver5

#2076 fix #2074 PermissionGroupsController::deleteのユニットテスト実装
  plugins/baser-core/src/Controller/Admin/PermissionGroupsController.php
  plugins/baser-core/tests/TestCase/Controller/Admin/PermissionGroupsControllerTest.php
Labels: Reviewed, ver5

#2101 fix #2094 Api/WidgetAreasController::update_widget のユニットテスト実装
  plugins/bc-widget-area/src/Controller/Api/Admin/WidgetAreasController.php
  plugins/bc-widget-area/tests/TestCase/Controller/Api/Admin/WidgetAreasControllerTest.php
Labels: ver5

#2102 Dev#2080 #2081 PermissionGroupsAdminServiceのユニットテスト
  plugins/baser-core/src/Service/Admin/PermissionGroupsAdminService.php
  plugins/baser-core/tests/TestCase/Service/Admin/PermissionGroupsAdminServiceTest.php
Labels: ver5

#2113 fix #2112 ThemeFoldersService::getNew のユニットテスト実装
  plugins/bc-theme-file/src/Service/ThemeFoldersService.php
  plugins/bc-theme-file/tests/TestCase/Service/ThemeFoldersServiceTest.php
Labels: ver5

#2124 fix #1968 BcDatabaseService::getMigrationsTable の のユニットテストを実装
  plugins/baser-core/src/Service/BcDatabaseService.php
  plugins/baser-core/tests/TestCase/Service/BcDatabaseServiceTest.php
Labels: ver5
