Repository baserproject/basercms, pull requests merged in 2024-04, with the labels that each got.

#3288 BlogHelper::_mergePostCountToTagsData のユニットテスト
  plugins/bc-blog/src/View/Helper/BlogHelper.php
  plugins/bc-blog/tests/TestCase/View/Helper/BlogHelperTest.php
Labels: Reviewed

#3304 fix #3303 カスタムコンテンツ 並び順の選択肢の中に「公開日付」が含まれていない問題を解決
  plugins/bc-custom-content/src/Service/CustomContentsService.php
  plugins/bc-custom-content/tests/TestCase/Service/CustomContentsServiceTest.php
Labels: Review

#3295 CustomContentHelper::clearCacheLinksのユニットテスト
  plugins/bc-custom-content/src/View/Helper/CustomContentHelper.php
  plugins/bc-custom-content/tests/TestCase/View/Helper/CustomContentHelperTest.php
Labels: Reviewed

#3330 add BcEditorTemplate_plugin
  plugins/bc-editor-template/src/BcEditorTemplatePlugin.php
  plugins/bc-editor-template/tests/BcEditorTemplatePluginTest.php
Labels: Reviewed

#3353 fix #3318 ユーザーグループ登録にて表示名重複が許されている
  plugins/baser-core/src/Model/Table/UserGroupsTable.php
  plugins/baser-core/tests/TestCase/Model/Table/UserGroupsTableTest.php
Labels: Reviewed

#3355 fix #2951 メール基本設定で各項目にスペースが登録できてしまう
  plugins/bc-mail/src/Model/Table/MailConfigsTable.php
  plugins/bc-mail/tests/TestCase/Model/Table/MailConfigsTableTest.php
Labels: Reviewed

#3343 Add Admin_MailFieldsController_edit
  plugins/bc-mail/src/Controller/Admin/MailFieldsController.php
  plugins/bc-mail/tests/TestCase/Controller/Admin/MailFieldsControllerTest.php
Labels: Reviewed

#3344 add Admin_MailFieldsController_add
  plugins/bc-mail/src/Controller/Admin/MailFieldsController.php
  plugins/bc-mail/tests/TestCase/Controller/Admin/MailFieldsControllerTest.php
Labels: Reviewed

#3351 add Admin_MailFieldsController_coppy
  plugins/bc-mail/src/Controller/Admin/MailFieldsController.php
  plugins/bc-mail/tests/TestCase/Controller/Admin/MailFieldsControllerTest.php
Labels: Reviewed

#3352 add Admin_MailFieldsController_delete
  plugins/bc-mail/src/Controller/Admin/MailFieldsController.php
  plugins/bc-mail/tests/TestCase/Controller/Admin/MailFieldsControllerTest.php
Labels: Reviewed

#3365 fix #3363 【テーマ：BcColumn　dev-5.1】エントリー詳細でエントリー名が二つ表示される
  plugins/bc-custom-content/src/View/Helper/BcCustomContentBaserHelper.php
  plugins/bc-front/templates/plugin/BcCustomContent/CustomContent/default/view.php
Labels: Reviewed

#3346 fix メールフィールド複製時、受信データ用テーブルを作り直す動作となっていることで、保持している受信データを削除している動作を調整
  app/webroot/theme/admin-third/Elements/admin/mail_fields/index_row.php
  lib/Baser/Plugin/Mail/Controller/MailFieldsController.php
  lib/Baser/Plugin/Mail/View/Elements/admin/mail_fields/index_row.php
Labels: Ver4

#3369 add MailFieldsTable_sourceMailField
  plugins/bc-mail/src/Model/Table/MailFieldsTable.php
  plugins/bc-mail/tests/TestCase/Model/Table/MailFieldsTableTest.php
Labels: Reviewed
