Repository baserproject/basercms, pull requests merged in 2024-02, with the labels that each got.

#3071 BlogHelper::parseContentNameのユニットテスト
  plugins/bc-blog/src/View/Helper/BlogHelper.php
  plugins/bc-blog/tests/TestCase/View/Helper/BlogHelperTest.php
Labels: Reviewed

#3052 BlogPostsService::getUrlのユニットテスト
  plugins/bc-blog/src/Service/BlogPostsService.php
  plugins/bc-blog/tests/TestCase/Service/BlogPostsServiceTest.php
Labels: Reviewed

#3068 BlogHelper::isBlogのユニットテスト
  plugins/bc-blog/src/View/Helper/BlogHelper.php
  plugins/bc-blog/tests/TestCase/View/Helper/BlogHelperTest.php
Labels: Reviewed

#3074 BlogHelper::postsのユニットテスト
  plugins/baser-core/src/View/Helper/BcBaserHelper.php
  plugins/bc-blog/src/View/Helper/BlogHelper.php
  plugins/bc-blog/tests/Factory/BlogCategoryFactory.php
  plugins/bc-blog/tests/Factory/BlogCommentFactory.php
  plugins/bc-blog/tests/Factory/BlogContentFactory.php
  plugins/bc-blog/tests/Factory/BlogPostBlogTagFactory.php
  plugins/bc-blog/tests/Factory/BlogPostFactory.php
  plugins/bc-blog/tests/Factory/BlogTagFactory.php
  plugins/bc-blog/tests/Scenario/BlogContentScenario.php
  plugins/bc-blog/tests/TestCase/Controller/Admin/BlogPostsControllerTest.php
  plugins/bc-blog/tests/TestCase/Controller/Api/Admin/BlogContentsControllerTest.php
  plugins/bc-blog/tests/TestCase/Service/BlogContentsServiceTest.php
  plugins/bc-blog/tests/TestCase/View/Helper/BlogHelperTest.php
  plugins/bc-custom-content/tests/TestCase/Model/Table/CustomLinksTableTest.php
  plugins/bc-front/templates/plugin/BcBlog/Blog/default/posts.php
Labels: Reviewed

#2917 fix #1081 【ブログ】アイキャッチ画像が常にブラウザキャッシュを利用されないQUERY_STRINGを発行している
  lib/Baser/Test/Case/View/Helper/BcFormHelperTest.php
  lib/Baser/Test/Case/View/Helper/BcUploadHelperTest.php
  lib/Baser/View/Helper/BcUploadHelper.php
Labels: Reviewed, ver4

#3121 fix #3120 カスタムコンテンツを２つ以上トップページなどで一覧表示させるとアイキャッチが取得できない問題を解決
  plugins/bc-custom-content/src/View/Helper/CustomContentHelper.php
Labels: Reviewed

#3114 fix #3098 【5.1】エディタテンプレート新規登録・編集で必須項目を記入せず、アイコン画像を入れ保存するとエラーが発生する【エディタテンプレート】
  plugins/baser-core/src/View/Helper/BcFormHelper.php
Labels: Reviewed

#3122 BlogHelper::isArchive のユニットテスト
  plugins/bc-blog/src/View/Helper/BlogHelper.php
  plugins/bc-blog/tests/TestCase/View/Helper/BlogHelperTest.php
Labels: Reviewed

#3011 fix #3010 [baserCMS5系]サブサイトのドメイン設定ができない問題を解決
  plugins/bc-admin-third/src/js/admin/sites/form.js
  plugins/bc-admin-third/templates/Admin/element/Sites/form.php
  plugins/bc-admin-third/webroot/js/admin/sites/form.bundle.js
  plugins/bc-admin-third/webroot/js/admin/sites/form.bundle.js.map
Labels: Review, Reviewed

#3086 ユニットテスト調整 BlogCommentsService::getBlogContent
  plugins/bc-blog/src/Service/BlogCommentsService.php
  plugins/bc-blog/tests/TestCase/Service/BlogCommentsServiceTest.php
Labels: Reviewed

#3113 BlogHelper::getBlogTemplates のユニットテスト
  plugins/bc-blog/src/View/Helper/BlogHelper.php
  plugins/bc-blog/tests/TestCase/Controller/BlogControllerTest.php
  plugins/bc-blog/tests/TestCase/View/Helper/BlogHelperTest.php
  plugins/bc-theme-file/tests/TestCase/Service/Admin/ThemeFilesAdminServiceTest.php
  plugins/bc-theme-file/tests/TestCase/Service/ThemeFoldersServiceTest.php
Labels: Reviewed

#3133 add BlogCommentsService::getNew
  plugins/bc-blog/src/Service/BlogCommentsService.php
  plugins/bc-blog/tests/TestCase/Service/BlogCommentsServiceTest.php
Labels: Reviewed

#3087 ユニットテスト BlogPostsTable::beforeSave
  plugins/bc-blog/src/Model/Table/BlogPostsTable.php
  plugins/bc-blog/tests/TestCase/Model/BlogPostsTableTest.php
Labels: Reviewed

#3132 BlogHelper::nextLink() のユニットテスト
  plugins/bc-blog/src/View/Helper/BlogHelper.php
  plugins/bc-blog/tests/TestCase/View/Helper/BlogHelperTest.php
Labels: Reviewed

#3134 BlogHelper::prevLink() のユニットテスト
  plugins/bc-blog/src/View/Helper/BlogHelper.php
  plugins/bc-blog/tests/TestCase/View/Helper/BlogHelperTest.php
Labels: Reviewed

#3085 ユニットテスト BlogCommentsService::add
  plugins/bc-blog/src/Service/BlogCommentsService.php
  plugins/bc-blog/tests/TestCase/Service/BlogCommentsServiceTest.php
Labels: Reviewed

#2988 fix #2987 BcBaserHelper::getThemeUrl()でサブサイトに設定しているテーマURLが取得できない動作を修正
  lib/Baser/Test/Case/View/Helper/BcBaserHelperTest.php
  lib/Baser/View/Helper/BcBaserHelper.php
Labels: Review, ver4
