Repository baserproject/basercms, pull requests merged in 2024-06, with the labels that each got.

#3436 add unitTest_CustomContentAdminHelper_isEnabledMoveUpEntry
  plugins/bc-custom-content/src/View/Helper/CustomContentAdminHelper.php
  plugins/bc-custom-content/tests/TestCase/View/Helper/CustomContentAdminHelperTest.php
Labels: Reviewed

#3439 add unitTest_MailHelper_getDescription
  plugins/bc-mail/src/View/Helper/MailHelper.php
  plugins/bc-mail/tests/TestCase/View/Helper/MailHelperTest.php
Labels: Reviewed

#3443 unitTest_CustomFieldsTable_decodeEntity
  plugins/bc-custom-content/src/Model/Table/CustomFieldsTable.php
Labels: Reviewed

#3454 add unitTest_User_getAuthPrefixes
  plugins/baser-core/src/Model/Entity/User.php
  plugins/baser-core/tests/TestCase/Model/Entity/UserTest.php
Labels: Reviewed

#3478 User::isEnableLoginAgentのユニットテスト
  plugins/baser-core/src/Model/Entity/User.php
  plugins/baser-core/tests/TestCase/Model/Entity/UserTest.php
  plugins/baser-core/tests/TestCase/View/Helper/BcBaserHelperTest.php
Labels: Reviewed

#3468 add unitTest_BcContentHelper_getJsonItems
  plugins/baser-core/src/View/Helper/BcContentsHelper.php
  plugins/baser-core/tests/TestCase/View/Helper/BcContentsHelperTest.php
Labels: Reviewed

#3470 add unitTest_BcFreezeHelper_password
  plugins/baser-core/src/View/Helper/BcFreezeHelper.php
  plugins/baser-core/tests/TestCase/View/Helper/BcFreezeHelperTest.php
Labels: Reviewed

#3489 MaildataHelper::control
  plugins/bc-mail/src/View/Helper/MaildataHelper.php
  plugins/bc-mail/tests/TestCase/View/Helper/MaildataHelperTest.php
Labels: Reviewed

#3500 BcArrayHelper::last
  plugins/baser-core/src/View/Helper/BcArrayHelper.php
  plugins/baser-core/tests/TestCase/View/Helper/BcArrayHelperTest.php
Labels: Reviewed

#3501 BcArrayHelper::first
  plugins/baser-core/src/View/Helper/BcArrayHelper.php
  plugins/baser-core/tests/TestCase/View/Helper/BcArrayHelperTest.php
Labels: Reviewed

#3504 BcUtil::pairToAssoc
  plugins/baser-core/src/Utility/BcUtil.php
  plugins/baser-core/tests/TestCase/Utility/BcUtilTest.php
Labels: Reviewed

#3515 BcBaserHelper::charset
  plugins/baser-core/src/View/Helper/BcBaserHelper.php
  plugins/baser-core/tests/TestCase/View/Helper/BcBaserHelperTest.php
Labels: Reviewed

#3519 BcBaserHelper::baseUrl
  plugins/baser-core/src/View/Helper/BcBaserHelper.php
Labels: Reviewed

#3535 Plugin::isAdminTheme
  plugins/baser-core/src/Model/Entity/Plugin.php
  plugins/baser-core/tests/TestCase/Model/Entity/PluginTest.php
Labels: Reviewed

#3538 BcBaserHelper::getContentsUrl() ユニットテストを調整
  plugins/baser-core/src/View/Helper/BcBaserHelper.php
  plugins/baser-core/tests/TestCase/View/Helper/BcBaserHelperTest.php
Labels: Reviewed

#3544 fix #3537【システム】管理画面でお気に入りの削除を行った直後にお気に入りの追加を行えない
  plugins/bc-admin-third/src/bc_favorite/js/admin/favorites/index.vue
  plugins/bc-admin-third/webroot/bc_custom_content/js/admin/custom_tables/form.bundle.js.map
  plugins/bc-admin-third/webroot/bc_favorite/js/admin/favorites/main.bundle.js
  plugins/bc-admin-third/webroot/bc_favorite/js/admin/favorites/main.bundle.js.map
Labels: Reviewed

#3549 fix #3523 【システム】管理画面ログイン後のリダイレクトが動作していない
  plugins/baser-core/src/Controller/AppController.php
Labels: Bug

#3480 User::isEditableUser のユニットテスト
  plugins/baser-core/src/Model/Entity/User.php
  plugins/baser-core/tests/TestCase/Model/Entity/UserTest.php
Labels: Reviewed

#3536 Plugin::isTheme:
  plugins/baser-core/src/Model/Entity/Plugin.php
  plugins/baser-core/tests/TestCase/Model/Entity/PluginTest.php
Labels: Reviewed

#3479 User::isDeletableUser のユニットテスト
  plugins/baser-core/src/Model/Entity/User.php
  plugins/baser-core/tests/TestCase/Model/Entity/UserTest.php
Labels: Reviewed

#3433 add unitTest_UploaderHelper_getFileUrl
  plugins/bc-uploader/src/View/Helper/UploaderHelper.php
  plugins/bc-uploader/tests/TestCase/View/Helper/UploaderHelperTest.php
Labels: Reviewed

#3469 add unitTest_BcFreezeHelper_number
  plugins/baser-core/src/View/Helper/BcFreezeHelper.php
  plugins/baser-core/tests/TestCase/View/Helper/BcFreezeHelperTest.php
Labels: Reviewed

#3520 BcContentsHelper::getSiteRoot
  plugins/baser-core/src/View/Helper/BcContentsHelper.php
  plugins/baser-core/tests/TestCase/View/Helper/BcContentsHelperTest.php
Labels: Reviewed

#2977 BcFormHelperのcontrolメソッドにafterControl追加
  plugins/baser-core/src/View/Helper/BcFormHelper.php
Labels: Reviewed

#3547 Cake\ORM\Table::find()の前後にイベントを追加
  plugins/baser-core/src/Model/Table/AppTable.php
  plugins/baser-core/tests/TestCase/Model/Table/AppTableTest.php
Labels: Reviewed, New
